config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  #get "/genres",      to: "genres#index"
  #get "/genres/:id",  to: "genres#show"

  #get '/directors',     to: "directors#index"
  #get '/directors/:id', to: "directors#show"

  #get '/movies',      to: "movies#index"
  #get "/movies/:id",  to: "movies#show"
  resources :movies, :directors, :genres
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
    validates :name, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
    validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_one_attached :cover
  
  validates :title, presence: true
  #validates :genre, presence: true
  #validates :synopsis, presence: true, length: { minimum: 10 }
  VALID_STATUSES = ['released', 'coming out']
  validates :status, inclusion: { in: VALID_STATUSES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.all
  end

  def show
    @director = Director.find(params[:id])
    @movies = Movie.all
  end

  def new
    @director = Director.new
  end

  def create
    @director = Director.new(director_params)

    if @director.save
      redirect_to @director
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @director = Director.find(params[:id])
  end

  def update
    @director = Director.find(params[:id])

    if @director.update(director_params)
      redirect_to @director
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @director = Director.find(params[:id])
    @director.destroy

    redirect_to root_path
  end
  

  private
    def director_params
      params.require(:director).permit(:name, :nationality, :birthdate, :favourite_genre)
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
    @movies = Movie.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)

    if @genre.save
      redirect_to @genre
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])

    if @genre.update(genre_params)
      redirect_to @genre
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy

    redirect_to root_path
  end

  private
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to @movie
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(movie_params)
      redirect_to @movie
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    redirect_to root_path
  end

  private
    def movie_params
      params.require(:movie).permit(:title, :release, :synopsis, :country, :runtime, :director, :genre, :status, :cover)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/directors/_form.html.erb
<p>(* campo obrigatório)</p>
<br>

<%= form_with model: director do |form| %>
  <div>
    <%= form.label :name %> <span>*</span><br>
    <%= form.text_field :name %>
    <% @director.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :nationality %><br>
    <%= form.text_field :nationality %>
  </div>

  <div>
    <%= form.label :birthdate %><br>
    <%= form.text_field :birthdate %>
  </div>

  <p>mudar o formatado de nascimento depois de modificar a tabela</p>
  
  <div>
  <%# form.label :birthdate %><br>
  <%#form.date_field :birthdate %>
  </div>

  <div>
    <%= form.label :favourite_genre %><br>
    <%= form.text_field :favourite_genre %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>


<br>
<%= link_to "HOME", root_path %>
<br>
<%= link_to "Lista de diretores", directors_path %>

app/views/directors/edit.html.erb
<h1>Editar informações:</h1>

<%= render "form", director: @director %>

app/views/directors/index.html.erb
<h1>Diretores</h1>

<ul>
  <% @directors.each do |director| %>
    <li>
        <%= link_to director.name, director %>
    </li>
  <% end %>
</ul>

<br>
<%= link_to "Cadastre um novo diretor", new_director_path %>
<br>
<%= link_to "HOME", root_path %>

app/views/directors/new.html.erb
<h1>Cadastre um novo(a) diretor(a):</h1>

<%= render "form", director: @director %>

app/views/directors/show.html.erb
<%= link_to "HOME", root_path %>
<br>
<%= link_to "Lista de diretores", directors_path %>
<br>

<h1><%= @director.name %></h1>

<p><strong>Nascimento:</strong> <%= @director.birthdate %></p>
<p><strong>Nacionalidade:</strong> <%= @director.nationality %></p>
<p><strong>Gênero favorito:</strong> <%= @director.favourite_genre %></p>

<h2>Filmes do diretor:</h2>

<ul>
  <% @movies.each do |movie| %>
    <% if movie.director == @director.name %>
      <li>
        <%= link_to movie.title, movie%>
      </li>
    <% end %>
  <% end %>
</ul>

<button><%= link_to "Editar", edit_director_path(@director) %></button>
<button><%= link_to "Excluir", director_path(@director), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Tem certeza que quer excluir o(a) diretor(a) '#{@director.name}'?"
                    } %></button>

app/views/genres/_form.html.erb
<p>(* campo obrigatório)</p>
<br>

<%= form_with model: genre do |form| %>
  <div>
    <%= form.label :name %> <span>*</span><br>
    <%= form.text_field :name %>
    <% @genre.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>


<br>
<%= link_to "HOME", root_path %>
<br>
<%= link_to "Lista de gêneros", genres_path %>

app/views/genres/edit.html.erb
<h1>Editar cadastro:</h1>

<%= render "form", genre: @genre %>

app/views/genres/index.html.erb
<h1>Gêneros</h1>

<ul>
  <% @genres.each do |genre| %>
    <li>
      <%= link_to genre.name, genre %>
    </li>
  <% end %>
</ul>

<br>
<%= link_to "Cadastrar novo gênero de filme", new_genre_path %>
<br>
<%= link_to "HOME", root_path %> 

app/views/genres/new.html.erb
<h1>Cadastre um novo gênero:</h1>

<%= render "form", genre: @genre %>

app/views/genres/show.html.erb
<%= link_to "HOME", root_path %>
<br>
<%= link_to "Lista de gêneros", genres_path %>
<br>

<h1><%= @genre.name %></h1>

<ul>
  <% @movies.each do |movie| %>
    <% if movie.genre == @genre.name %>
      <li>
        <%= link_to movie.title, movie%>
      </li>
    <% end %>
  <% end %>
</ul>



<button><%= link_to "Editar", edit_genre_path(@genre) %></button>
<button><%= link_to "Excluir", genre_path(@genre), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Tem certeza que quer excluir o gênero '#{@genre.name}'?"
                    } %></button>

app/views/home/index.html.erb
<h1>- Catálogo de filmes -</h1>

<p><%= link_to "Filmes", movies_path %></p>
<p><%= link_to "Diretores", directors_path %></p>
<p><%= link_to "Gêneros", genres_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moviesdb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<p>(* campo obrigatório)</p>
<br>

<%= form_with model: movie do |form| %>
  <div>
    <%= form.label :title %> <span>*</span><br>
    <%= form.text_field :title %>
    <% @movie.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :release %><br>
    <%= form.number_field :release, in: 1900..2100, step: 1  %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['released', 'coming out'], selected: 'released' %>
  </div>


  <div>
    <%= form.label :country %><br>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :runtime %><br>
    <%= form.text_field :runtime %>
  </div>

  <div>
    <%= form.label :director %><br>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.label :genre %><br>
    <%= form.text_field :genre %>
  </div>

  <div>
    <%= form.label :synopsis %><br>
    <%= form.text_area :synopsis %>
  </div>

  <div>
    <%= form.label :cover %><br>
    <%= form.file_field :cover %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<br>
<%= link_to "HOME", root_path %>
<br>
<%= link_to "Lista de filmes", movies_path %>

app/views/movies/edit.html.erb
<h1>Editar informações:</h1>

<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<h1>Filmes lançados:</h1>

<ul>
  <% @movies.each do |movie| %>

    <% if movie.status == 'released' %>
      <li>
        <%= link_to "#{movie.title} (#{movie.release})", movie%>
      </li>
    <% end %>

  <% end %>
</ul>

<h1>Próximos Lançamentos:</h1>

<ul>
  <% @movies.each do |movie| %>

    <% if movie.status == 'coming out' %>
      <li>
        <%= link_to "#{movie.title} (#{movie.release})", movie%>
      </li>
    <% end %>

  <% end %>
</ul>

<br>
<%= link_to "Cadastre um novo filme", new_movie_path %>
<br>
<%= link_to "HOME", root_path %>

app/views/movies/new.html.erb
<h1>Cadastre um novo filme:</h1>

<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<%= link_to "HOME", root_path %>
<br>
<%= link_to "Lista de filmes", movies_path %>
<br>

<h1><%= @movie.title %></h1>

<p><strong>Ano de lançamento:</strong> <%= @movie.release %></p>
<p><strong>País:</strong> <%= @movie.country %></p>
<p><strong>Duração:</strong> <%= @movie.runtime %> minutos</p>
<p><strong>Diretor:</strong> <%= @movie.director %></p>
<p><strong>Gênero:</strong> <%= @movie.genre %></p>

<h3>Sinopse:</h3>
<p><%= @movie.synopsis %></p>

<p>
  <strong>Capa:</strong> <br>
  <%= image_tag @movie.cover %>
</p>

<button><%= link_to "Editar", edit_movie_path(@movie) %></button>
<button><%= link_to "Excluir", movie_path(@movie), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Tem certeza que quer excluir o filme '#{@movie.title}'?"
                    } %></button>